// app/layout.tsx
import type { Metadata } from "next";
import { myCustomFont } from "@/src/lib/styles/fonts";
import { AnimatePresence } from "framer-motion";
import "./globals.css";
import BackgroundShader from "./components/common/Shader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myCustomFont.variable} antialiased`}>
        <AnimatePresence mode="wait">
          <BackgroundShader />
          {children}
        </AnimatePresence>
      </body>
    </html>
  );
}